### ISSUE TITLE
Incorporate PDF generation into main server code.

### ISSUE THREAD

**Issue by kshowalter** [FSEC/SPD#12]

**Comment by kshowalter** [comment]
Commit https://github.com/FSEC/SPD/commit/2d721d334d38097c22623c2750b93720e4b40984 incorporates Tom's code. 

Is testing needed, or is this closed?

**Comment by kshowalter** [comment]
The PDF download link still goes to an external server.

**Comment by LegendaryTom** [comment]
I believe the code in mk_permit.js is working.  There's one big todo left though, which is looking up the spec sheets for the module and inverter to include.

**Comment by kshowalter** [comment]
I switched the link to the local route, with the assumption that the real PDF spec sheets will be available before it needs to be demonstrated. We can easily switch back if needed.
