### ISSUE TITLE
Add building details to drawing

### ISSUE THREAD

**Issue by kshowalter** [FSEC/SPD#17]
We need to diagram what measurements of the building the inputs are asking for. Stephen provided the example below.
![solar plans designer3](https://cloud.githubusercontent.com/assets/4062195/10026336/38e12940-612f-11e5-8cc1-4f738a023bff.png)

**Comment by kshowalter** [comment]
If we switch to the tabbed interface, I do not think we need the preview drawings in there current form. Do we need to add the plan view to the roof dimension diagram?

**Comment by kshowalter** [comment]
"Eave Width" is the label for the parameter "width1" that is used in many calculations. Do we need an eave_length parameter? Is that equivalent to width1? Is it going to be stored under roof, structural, site, or S-001? It would be good to make an attempt at a complete list of user inputs and what section they will be in. Any calculations will refer to this value as [section].eave_length, so it would be less confusing to set that section now.

**Comment by Barkaszi** [comment]
![solar plans designer](https://cloud.githubusercontent.com/assets/13969865/10058444/78ff6c0a-6213-11e5-93cc-2e31289c0982.png)

**Comment by kshowalter** [comment]
"create new system" and "delete system" do what they say. See issue https://github.com/FSEC/SPD/issues/18.

**Comment by kshowalter** [comment]
![roof-styles-1](https://cloud.githubusercontent.com/assets/4062195/10368401/05fc278e-6da3-11e5-8bbe-39a943f1b89c.gif)
![030912steps5_roof_design_types](https://cloud.githubusercontent.com/assets/4062195/10368404/0afeb62a-6da3-11e5-9fba-ab98dbb4e260.jpg)

**Comment by kshowalter** [comment]
When reviewing satellite imagery, it is difficult to find more than one or two houses among hundreds that is close enough to the these simple roof models to make the models usable. Does it make sense to show any details of the building until we can accurately model the whole building, assuming we need to? 

Should we just model the usable roof area? This would allow the selection of multiple areas as is common on real installations. ex: 10 modules fit on the south roof, and 4 fit on the west slope, or the second floor.

Number of installation locations: [ n  ]
roof section 1 width: [   ] 
roof section 1 height: [   ]
roof section 1 slope: [ 2:12, 3:12, ... ]
roof section 1 direction: [ S, S 5 E, S 10 E, ... S 5 W, ...   ]

roof section n width: [   ] 
roof section n height: [   ]
roof section n slope: [ 2:12, 3:12, ... ]
roof section n direction: [ S, S 5 E, S 10 E, ... S 5 W, ...   ]

Then we generate a structural sheet for each roof section.

**Comment by kshowalter** [comment]
From Stephen:
![Uploading Solar Plans Designer 2015-10-08 A.png…]()

**Comment by kshowalter** [comment]
![roof_area_selection](https://cloud.githubusercontent.com/assets/4062195/10497214/bc30b4c2-7292-11e5-89ab-fce831fb67fb.png)

**Comment by kshowalter** [comment]
We have decided to only define the parts of the roof that we need. Right now that is the roof height to check the max average building height. 

Sections of the roof will be defined by the user, and the modules will be placed in these sections.

![screenshot from 2015-10-20 09 50 54](https://cloud.githubusercontent.com/assets/4062195/10609143/3c8658f8-7710-11e5-9b03-eb202aa82b0d.png)
