### ISSUE TITLE
Unable to create a user with latest dev build

### ISSUE THREAD

**Issue by wmollenkopf** [FSEC/SPD#21]
Whenever an error is attempted to be created, the server bugs out.
The error is with ./SPD/lib/update_options.js
Line 41: id = System_data.findOne( { system_id:system_id, section_name:section_name, value_name:'voltage' })._id;

I don't know much about what this is supposed to be doing? But it's failing to assign a value to id, causing a crash that causes create user to fail.

**Comment by kshowalter** [comment]
That line looks up the database id of an input specification in the database, so it can change the options (for the drop list) in the next few lines. That is run anytime the AC loadcenter type is changed, including when it is created. What errors are you seeing? My local version is able to create a new user without problem. It sounds like that is being run before that value is in the database, but it should only run due to a change in that value in the database.

**Comment by wmollenkopf** [comment]
I've been trying to run with a clean cloned copy from the dev branch so I could extract any additional errors that might be useful to debug.

Currently I'm unable to start any Meteor server at all.
I'm getting the error:
william@SPDDEV:/srv/samba/william/temp/SPD$ meteor --port 3001
[[[[[ /srv/samba/william/temp/SPD ]]]]]

=> Started proxy.
=> Started MongoDB.

/home/william/.meteor/packages/meteor-tool/.1.1.4.1c1ed6m++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
                                                throw(ex);
                                                      ^
Error: EACCES, open '/home/william/.meteorsession'
    at Object.Future.wait (/home/william/.meteor/packages/meteor-tool/.1.1.4.1c1ed6m++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper [as readFile] (/home/william/.meteor/packages/meteor-tool/.1.1.4.1c1ed6m++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:1350:24)
    at readSessionData (/home/william/.meteor/packages/meteor-tool/.1.1.4.1c1ed6m++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/auth.js:134:27)
    at Object.exports.getSessionId (/home/william/.meteor/packages/meteor-tool/.1.1.4.1c1ed6m++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/auth.js:845:32)
    at /home/william/.meteor/packages/meteor-tool/.1.1.4.1c1ed6m++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/stats.js:64:23
    - - - - -

----------------------------------------

I had this problem last week but I think it was because of the firewall not having the port available, but that was resolved. 
I tried port 80, 8080, 3000 (responds with something is already running on 3000), 30001

Anyways, the create account error I saw was one under the username and password field.
I believe it had small font that read: "Internal Server Error" and that was all.

**Comment by kshowalter** [comment]
The error report references a node module in the .meteor directory, so it may be an incompatibility issue between the version of node, meteor, and the specific node module that are installed on your machine. It seems to be throwing the error before any project specific code is loaded. 

I have Meteor 1.1.0.3 on my dev machine, the server is probably similar. Version 1.2 has some module API changes that breaks one of the meteor modules in the project. Meteor will not let you upgrade until it is fixed, but if you did a fresh install, you may be on 1.2.

I had to make the following change to one of the packages to upgrade Meteor:
https://github.com/meteorhacks/npm/issues/95#issuecomment-137534873
and that change should end up in out dev branch when I merge the branch I am working on. You might fix that file now, to see if it helps.

Meteor's default port is 3000, so you may have an instance of it running in the background.

**Comment by wmollenkopf** [comment]
I checked and currently the installed meteor is 1.1.0.3.

I made the change to the package.js file and while the server did technically start, several screens worth of errors appeared.

And the web page responds with:

------------------------------------------------------------

Your app is crashing. Here's the latest log.

Errors prevented startup:

While reading package from `/srv/samba/william/temp/SPD/packages/npm-container`:
package.js:27:7: Object #<PackageAPI> has no method 'addAssets'

Your application has errors. Waiting for file change.
Started MongoDB.

------------------------------------------------------------


So I'm still not sure what's wrong with things here.

**Comment by kshowalter** [comment]
I had to change that method call in that package to be compatible with Meteor 1.2, so you may need to upgrade Meteor. Since I altered an external package, updates to that package may undo the change. The package maintainer mentioned fixing it in a future update, so it may not be an issue. 

I have done a fresh clone of the repository, and it worked with 1.2 installed. Hopefully that will fix it for you.

**Comment by wmollenkopf** [comment]
When I logged into a shell today to check the version it appears as though it was already upgraded to 1.2.0.1:

--------------------------

william@SPDDEV:~$ meteor --version
Meteor 1.2.0.1

--------------------------

So I made a new directory, cloned git, switched to branch and ran meteor on an available port, 3001

--------------------------

william@SPDDEV:/srv/samba/william/temp/SPD$ sudo meteor --port 3001
[[[[[ /srv/samba/william/temp/SPD ]]]]]

=> Started proxy.
=> Started MongoDB.
W20151005-13:23:13.355(-4)? (STDERR)
W20151005-13:23:13.357(-4)? (STDERR) /home/william/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151005-13:23:13.358(-4)? (STDERR)                                            throw(ex);
W20151005-13:23:13.358(-4)? (STDERR)                                                  ^
W20151005-13:23:13.358(-4)? (STDERR) Error: libclntsh.so.12.1: cannot open shared object file: No such file or directory
W20151005-13:23:13.359(-4)? (STDERR)     at Module.load (module.js:356:32)
W20151005-13:23:13.359(-4)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151005-13:23:13.359(-4)? (STDERR)     at Module.require (module.js:364:17)
W20151005-13:23:13.359(-4)? (STDERR)     at require (module.js:380:17)
W20151005-13:23:13.360(-4)? (STDERR)     at Object.<anonymous> (/srv/samba/william/temp/SPD/.meteor/local/isopacks/npm-container/npm/node_modules/oracledb/lib/oracledb.js:23:15)
W20151005-13:23:13.360(-4)? (STDERR)     at Module._compile (module.js:456:26)
W20151005-13:23:13.360(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20151005-13:23:13.360(-4)? (STDERR)     at Module.load (module.js:356:32)
W20151005-13:23:13.361(-4)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151005-13:23:13.361(-4)? (STDERR)     at Module.require (module.js:364:17)
=> Exited with code: 8
(repeats over and over)

-------------------------------------------

Tried again without making any changes but this time different results:

-------------------------------------------

william@SPDDEV:/srv/samba/william/temp/SPD$ meteor --port 3001
Retrying after error { [Error: SQLITE_CANTOPEN: unable to open database file] stack: [Getter] }
Retrying after error { [Error: SQLITE_CANTOPEN: unable to open database file] stack: [Getter] }

/home/william/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
                                                throw(ex);
                                                      ^
Error: SQLITE_CANTOPEN: unable to open database file
    at Object.Future.wait (/home/william/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at [object Object]._.extend._execute (/tools/packaging/catalog/catalog-remote.js:368:22)
    at /tools/packaging/catalog/catalog-remote.js:145:10
    at [object Object]._.extend._retry (/tools/packaging/catalog/catalog-remote.js:157:16)
    at new Db (/tools/packaging/catalog/catalog-remote.js:144:8)
    at [object Object]._.extend.initialize (/tools/packaging/catalog/catalog-remote.js:703:15)
    at /tools/cli/main.js:748:20
    - - - - -

--------------------------
I ran apt-get update, apt-get upgrade, reboot and ended up having the same exact issues as metioned above (except this time no more SQLITE_CANTOPEN error)

I'll have to talk with Tom when he's available to see what's up with the server since I think he installed our copy of meteor 1.1.x.x and performed the update to 1.2.0.1

Maybe there was something he did with his Tom user that needs to be applied to my William user still. I'm not sure.

**Comment by wmollenkopf** [comment]
I worked with Tom and it looks like I was missing some environment and path details that his user account had that mine did not have (but should have had it seems).

With a lot of trial and error it turns out that my solution after setting those variables up was to also delete my .meteor and .meteorsession directories within my home directory.
As well as reclone the repository and then try running meteor.
It appears to be running now with expected runtime errors due to a previous commit into the dev branch.
Once Tom has resolved those, I'll re-attempt to configure the (small) PDF code changes I had made before, commit, fetch, pull, and push.
And continue working from there on.

**Comment by kshowalter** [comment]
I do not have a version with the oracledb module included yet. I may run into the same problems. Do you think this was just a problem with your account on the server, or are there steps needed to make that module work on any machine?

**Comment by wmollenkopf** [comment]
It's probably likely you'll have the same issues then if you have the latest code.
Details about the oracle module can be found under: \SSR\Projects\SPD\Code\OracleClient

**Comment by LegendaryTom** [comment]
I believe that the version of node (and npm) that meteor was using the build the node-oracledb module is v0.10.25.  The module needs at least v0.10.28.  We ended up downloading a newer version of node, and editing the path variables before starting meteor.  This seemed to work.  If you follow every step in that document exactly (including the ones where for testing the module outside of meteor) then it should work for you.

**Comment by kshowalter** [comment]
Maybe we should stick to the JSON until we can fix this.
I updated meteor last week, and this file: 
.meteor/local/build/.node_version.txt 
Lists the version as v0.10.40

The current version of node is 4.1.2.
