### ISSUE TITLE
 Error: $MONGO_OPLOG_URL must be set to the 'local' database of a Mongo replica set

### ISSUE THREAD

**Issue by wmollenkopf** [FSEC/SPD#25]
Anyone else having this error? Or know how to resolve it?

I haven't modified any code, I simply performed a git fetch then a git pull and this is the error I receive when I try to run meteor on port 3001

**Comment by kshowalter** [comment]
I have not seen the error. You only see it when you run on 3001, but not on 3000? When was the last time you ran 'meteor update'?

**Comment by wmollenkopf** [comment]
I don't think I've run meteor update at all personally. I'm not sure if Tom has on the machine or not though.
I'm guessing I should do that then?

**Comment by wmollenkopf** [comment]
meteor update --patch
did the trick.

"SPD: updated to Meteor 1.2.0.2."
