### ISSUE TITLE
Add new electrical sheets to drawing

### ISSUE THREAD

**Issue by kshowalter** [FSEC/SPD#27]
From Stephen:
"Attached is a good example of a comprehensive electrical plan.
Most all of the information we need to include is shown and it is a good reference.
However, it is not legible on an 8x11 sheet. It would need to be broken into separate sheets so the details can be read at that scale." [0010Do.TES_FSEC_10KWr1.pdf](https://github.com/FSEC/SPD/files/16832/0010Do.TES_FSEC_10KWr1.pdf)

**Comment by BiriKomori** [comment]
https://www.npmjs.com/package/scissors

This looks like it might do the trick. 
If we can get the dimensions of the large dimension pdf page, then all we'd have to do is iterate through the large document and generate cropped portions to then be combined into a multi-page 8x11 pdf file.

This library might also be useful for many other related tasks to PDF manipulation. I haven't tested it or anything, but it's a thought.

**Comment by kshowalter** [comment]
Example included in https://github.com/FSEC/SPD/issues/58

Closed for being to vague.
