### ISSUE TITLE
Forgot Password doesn't work. 

### ISSUE THREAD

**Issue by ghost** [FSEC/SPD#33]
Need to implement MAIL_URL on server I believe.
(My local server reported something along those lines to me when I tried, and the production server never sent me an e-mail so I'm assuming it has a similar, if not same, issue.)

**Comment by kshowalter** [comment]
Does the local app user system need to be developed, or will it use a seperated FSEC user system?

**Comment by kshowalter** [comment]
The current plan is to have user registration handled outside this application.
