### ISSUE TITLE
Is System Name textbox field used for anything?

### ISSUE THREAD

**Issue by wmollenkopf** [FSEC/SPD#34]
As the title asks, does the System Name textbox field next to the list of Systems drop down serve any purpose?

It doesn't really seem like it does, but that it probably should be doing something, right?

I'm not sure if this is a bug in that it's supposed to actually append the text field name to the list of systems or not.

**Comment by kshowalter** [comment]
It is saved with the system info, but not used in the drawing. It is just a convenience for the user, so they don't have to remember the system ID.

**Comment by wmollenkopf** [comment]
Since it's meant as only a convenience for the user, would it be a good idea to have the names appear in the Systems [1]..[n] drop down list instead of the numbered method?

**Comment by kshowalter** [comment]
The name appears in the drop down list for me. We need something in addition to the name when a name is not specified.

**Comment by wmollenkopf** [comment]
Ah, I tested with Chrome and IE and those appear to work fine, but it doesn't do anything in Firefox.

**Comment by wmollenkopf** [comment]
Should be fixed with #47f8d18 (will ninja edit this with correct link format)
