### ISSUE TITLE
System Name entered input box text remains throughout creating/deleting systems.

### ISSUE THREAD

**Issue by ghost** [FSEC/SPD#35]
Is the System Name field supposed to clear the text whenever a system is added or deleted?

If it's supposed to, it's not for me.

**Comment by kshowalter** [comment]
The input box next to the system selection? That should update to the active (selected) system, or be empty when nothing is selected. I guess it could be greyed out when not needed.

**Comment by kshowalter** [comment]
System name input is disabled when no system is selected. https://github.com/FSEC/SPD/commit/efe58d436e31769e9d6d67023ad40312c4b0436c
