### ISSUE TITLE
Weather Data Issues

### ISSUE THREAD

**Issue by ghost** [FSEC/SPD#36]
Risk Category 1,Risk Category 2,Risk Category 3,Low Temp,High Temp Max,High Temp
all retain their values when the new system creation is used. 
(Similar to how checkboxes remain as well)

Scenario:
Create a system that has proper Risk Category values.
Ensure that's saved into the DB
Click Create New System.
The same values remain displayed on the page

I have some systems that appear to have the weather data that was carried over from what I thought was purely due to that visibility bug, carry over and save into the database as well using the same scenario described.

It's kinda buggy in that regard it seems like.

**Comment by kshowalter** [comment]
Those values need to be saved to the user_systems database. I will look into it.

**Comment by kshowalter** [comment]
This should be fixed with the rebuilding of the data storage format.
