### ISSUE TITLE
System Number In drop down numbers in a weird way

### ISSUE THREAD

**Issue by ghost** [FSEC/SPD#37]
I'm not sure on the solution to this one...
Scenario:
If you have 5 systems, they're listed in the drop down list as:
[1],[2],[3],[4],[5]

If you delete anything other than 5, for example [3] is deleted.
If you then create a system, you'll have a list of systems of:
[1],[2],[4],[5],[5]

It's just really weird.

If you delete, [1], and create a system, [2] and create a system, and so on.
You'll get a list of [4],[5],[5],[5],[5]
if you delete [4] and create a system, you'll get:
[5],[5],[5],[5],[5]

If you delete any of the [5]s that isn't the final [5] and create a system you'll get another [5]

If you delete the, let's say the first [5], then the last [5] and create a system you'll get a list of:
[5],[5],[5],[4]

Which is even more weird.

I don't understand the intended logic behind the numbering system at all, and I'm even more confused with the System Name and how it's supposed to be used.

Maybe the [1] to [n] numbering could/should instead be generated dynamically on page render based on the number of elements on the list alone and use the system names to act as actual identifiers?

**Comment by kshowalter** [comment]
If you have n systems defined, the new one will be n+1. I do not think these numbers will be permanent, so I did not define a more complex system. At the rate these things go, we probably should have a better temporary system.

**Comment by kshowalter** [comment]
fixed https://github.com/FSEC/SPD/commit/1e1fddad9da8b0d7899dec5ca2aeda6ca78a5eee
